version: "3"
services:
  db:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
  api:
    build: ./api
    links:
      - db:db
    environment:
      DB_HOST: db
      SECRET_KEY: zron2flb9394eoq0nho4amf6g0ewclg030h
    ports:
      - "8000:8000"
